<?php

function gcba_recibos_sueldo_views_pre_render(&$view) {
	if ($view->name === "recibos_sueldo") {
		if ($view->result) {
			$view->result[0]->fileUrl = gcba_recibos_sueldo_get_filename($view->result[0]->nid);
			$parsedDate = date_parse_from_format("Y-m-dTH:i:s", $view->result[0]->_field_data['nid']["entity"]->field_mes_y_ano["und"][0]["value"]);
			$view->result[0]->month = gcba_recibos_sueldo_get_month($parsedDate["month"]);
		}
		list($maxYear, $minYear) = gcba_recibos_sueldo_get_year_boundaries();
		$view->yearMinBoundary = $minYear;
		$view->yearMaxBoundary = $maxYear;
		$dateContextualFilter = date_parse_from_format("Y-m", $view->args[0]);
		$view->selectedMonth = $dateContextualFilter["month"];
	}
	return $view;
}

function gcba_recibos_sueldo_get_filename($nodeId) {
	global $user;
	$nroCuil = $user->name;
	$currentFileUri = db_query("SELECT uri FROM file_managed AS fm WHERE fm.fid IN (SELECT frs.field_recibos_sueldo_fid FROM field_data_field_recibos_sueldo AS frs WHERE entity_id = ". $nodeId . ") AND fm.filename LIKE '" . $nroCuil . "%'")->fetchField();
	if (!empty($currentFileUri)) {
		return file_create_url($currentFileUri);
	}
	return "";
}

function gcba_recibos_sueldo_get_year_boundaries() {
	//Ver que onda si no hay ningun recibo
	$result = db_query("SELECT MIN(DATE_FORMAT(field_mes_y_ano_value, '%Y')) AS min, MAX(DATE_FORMAT(field_mes_y_ano_value, '%Y')) AS max FROM field_data_field_mes_y_ano")->fetch();
	return array($result->max, $result->min);
}

function gcba_recibos_sueldo_get_month($month) {
	switch($month) {
		case 1:
			return t("January");
		case 2:
			return t("February");
		case 3:
			return t("March");
		case 4:
			return t("April");
		case 5:
			return t("May");
		case 6:
			return t("June");
		case 7:
			return t("July");
		case 8:
			return t("August");
		case 9:
			return t("September");
		case 10:
			return t("October");
		case 11:
			return t("November");
		case 12:
			return t("December");
	}
}
